// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using programa_consultorio.Data;

#nullable disable

namespace programa_consultorio.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220923192351_Criacao-Inicial2")]
    partial class CriacaoInicial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("programa_consultorio.Models.Tarefas", b =>
                {
                    b.Property<int>("id_tarefa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_tarefa");

                    b.Property<double>("custo_tarefa")
                        .HasColumnType("double")
                        .HasColumnName("custo_tarefa");

                    b.Property<DateOnly>("data_limite")
                        .HasColumnType("date")
                        .HasColumnName("data_limite");

                    b.Property<string>("nome_tarefa")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome_tarefa");

                    b.Property<int>("ordem_apres")
                        .HasColumnType("int")
                        .HasColumnName("ordem_apres");

                    b.HasKey("id_tarefa");

                    b.ToTable("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
